# SPDX-FileCopyrightText: 2024 Jan Schmitz <schmitz@num.uni-sb.de>
#
# SPDX-License-Identifier: CC0-1.0

name: "Nix tests"
on:
  pull_request:
  push:
jobs:
  nix-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build
    - run: nix run
    - run: nix build .#epsteinlib_dbg
    - run: nix run .#epsteinlib_dbg
    - run: nix flake check
    - run: nix develop -c tests
    - run: nix develop -c docs
