version: "3.4"

services:
  site:
    # Possible error:
    #
    #    fatal: unsafe repository ('/src' is owned by someone else)
    #
    # This is because Git 2.35.2 added this check as a security fix. The
    # non-minimal image has an older version of Git, so it doesn't complain.
    # Can be fixed with a .gitconfig containing:
    #
    #     [safe]
    #         directory = /home/repon

    image: "hugomods/hugo:0.140.0"
    command: "server"
    volumes:
      - "./:/src"
    ports:
      - "1313:1313"
